# Generated by Django 5.0.3 on 2024-05-27 13:20

import uuid

import django.contrib.auth.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		("auth", "0012_alter_user_first_name_max_length"),
	]

	operations = [
		migrations.CreateModel(
			name="Portal",
			fields=[
				(
					"id",
					models.UUIDField(
						default=uuid.uuid4,
						editable=False,
						primary_key=True,
						serialize=False,
					),
				),
				("name", models.CharField(max_length=30)),
				("content", models.JSONField(default=dict)),
				("created_at", models.DateTimeField(default=django.utils.timezone.now)),
			],
		),
		migrations.CreateModel(
			name="User",
			fields=[
				(
					"user_ptr",
					models.OneToOneField(
						auto_created=True,
						on_delete=django.db.models.deletion.CASCADE,
						parent_link=True,
						primary_key=True,
						serialize=False,
						to=settings.AUTH_USER_MODEL,
					),
				),
				("created_at", models.DateTimeField(default=django.utils.timezone.now)),
				(
					"portal",
					models.ForeignKey(
						on_delete=django.db.models.deletion.CASCADE, to="core.portal"
					),
				),
			],
			options={
				"verbose_name": "user",
				"verbose_name_plural": "users",
				"abstract": False,
			},
			bases=("auth.user",),
			managers=[
				("objects", django.contrib.auth.models.UserManager()),
			],
		),
	]
