# Generated by Django 5.0.3 on 2024-05-24 13:04

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = []

	operations = [
		migrations.CreateModel(
			name="UMalang",
			fields=[
				(
					"id",
					models.UUIDField(
						default=uuid.uuid4, primary_key=True, serialize=False
					),
				),
				("content", models.JSONField(default=dict)),
				("created_at", models.DateTimeField(default=django.utils.timezone.now)),
			],
		),
	]
