# Generated by Django 5.0.3 on 2024-05-24 13:35

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("api", "0001_initial"),
	]

	operations = [
		migrations.AlterField(
			model_name="umalang",
			name="id",
			field=models.UUIDField(
				default=uuid.uuid4, editable=False, primary_key=True, serialize=False
			),
		),
	]
