# Generated by Django 5.0.3 on 2024-05-27 12:15

import uuid

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		("api", "0002_alter_umalang_id"),
	]

	operations = [
		migrations.CreateModel(
			name="Portal",
			fields=[
				(
					"id",
					models.UUIDField(
						default=uuid.uuid4,
						editable=False,
						primary_key=True,
						serialize=False,
					),
				),
				("name", models.CharField(max_length=30)),
				("content", models.JSONField(default=dict)),
				("created_at", models.DateTimeField(default=django.utils.timezone.now)),
			],
		),
		migrations.DeleteModel(
			name="UMalang",
		),
	]
