# Generated by Django 5.0.3 on 2024-05-27 13:20

from django.db import migrations


class Migration(migrations.Migration):
	dependencies = [
		("api", "0003_portal_delete_umalang"),
	]

	operations = [
		migrations.DeleteModel(
			name="Portal",
		),
	]
