"""
Django settings for drexfall project.

Generated by 'django-admin startproject' using Django 5.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import nltk
import requests
from corsheaders.defaults import default_headers
from dotenv import load_dotenv
from drexfall.jwt_conf import SIMPLE_JWT
from imagekitio import ImageKit

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv()
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = "RENDER" not in os.environ

DOMAIN = os.getenv('DOMAIN')
PORT = os.getenv('PORT')
ALLOWED_HOSTS = [f".{DOMAIN}"]
DOMAIN_DATA = requests.get(
	url="https://api.render.com/v1/services/srv-co4h0mq1hbls73bt47f0/custom-domains?limit=20",
	headers={
		"accept": "application/json",
		"authorization": f"Bearer {os.getenv('RENDER_BEARER_TOKEN')}"
	}
)

RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
	ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)

# Application definition

INSTALLED_APPS = [
	'core.apps.CoreConfig',
	'scan.apps.ScanConfig',
	'profiles.apps.ProfilesConfig',
	'submit.apps.SubmitConfig',
	'api.apps.ApiConfig',
	'django_hosts',
	"django.contrib.admin",
	"django.contrib.auth",
	"django.contrib.contenttypes",
	"django.contrib.sessions",
	"django.contrib.messages",
	"django.contrib.staticfiles",
	'rest_framework',
	'rest_framework_simplejwt.token_blacklist',
	"corsheaders",
]

MIDDLEWARE = [
	'django_hosts.middleware.HostsRequestMiddleware',
	"django.middleware.security.SecurityMiddleware",
	"corsheaders.middleware.CorsMiddleware",
	'whitenoise.middleware.WhiteNoiseMiddleware',
	"django.contrib.sessions.middleware.SessionMiddleware",
	"django.middleware.common.CommonMiddleware",
	"django.middleware.csrf.CsrfViewMiddleware",
	"django.contrib.auth.middleware.AuthenticationMiddleware",
	"django.contrib.messages.middleware.MessageMiddleware",
	"django.middleware.clickjacking.XFrameOptionsMiddleware",
	'django_hosts.middleware.HostsResponseMiddleware'
]
DEFAULT_HOST = 'core'
ROOT_URLCONF = "drexfall.urls"
ROOT_HOSTCONF = 'drexfall.hosts'
PARENT_HOST = f"{DOMAIN}:{PORT}" if DEBUG else DOMAIN
REST_FRAMEWORK = {
	# Use Django's standard `django.contrib.auth` permissions,
	# or allow read-only access for unauthenticated users.
	# 'DEFAULT_PERMISSION_CLASSES': [
	#     'rest_framework.permissions.IsAuthenticatedOrReadOnly'
	# ],
	'DEFAULT_AUTHENTICATION_CLASSES': [
		'rest_framework_simplejwt.authentication.JWTAuthentication',
	],
	'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
	'PAGE_SIZE': 10,
	'DEFAULT_PARSER_CLASSES': (
		'rest_framework.parsers.JSONParser',
		'rest_framework.parsers.FormParser',
		'rest_framework.parsers.MultiPartParser',
	),
}

TEMPLATES = [
	{
		"BACKEND": "django.template.backends.django.DjangoTemplates",
		"DIRS": [BASE_DIR / "templates"],
		"APP_DIRS": True,
		"OPTIONS": {
			"context_processors": [
				"django.template.context_processors.debug",
				"django.template.context_processors.request",
				"django.contrib.auth.context_processors.auth",
				"django.contrib.messages.context_processors.messages",
			],
		},
	},
]

WSGI_APPLICATION = "drexfall.wsgi.application"

# Database
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases

DATABASES = {
	'default': {
		'ENGINE': 'django.db.backends.postgresql_psycopg2',
		'NAME': os.getenv('DATABASE_NAME'),
		'USER': os.getenv('DATABASE_USER'),
		'PASSWORD': os.getenv('DATABASE_PASSWORD'),
		'HOST': os.getenv('DATABASE_HOST'),
		'PORT': os.getenv('DATABASE_PORT'),
	}
}

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
	{
		"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
	},
	{
		"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
	},
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
	os.path.join(BASE_DIR, 'static'),
)

# This production code might break development mode, so we check whether we're in DEBUG mode
if not DEBUG:  # Tell Django to copy static assets into a path called `staticfiles` (this is specific to Render)
	STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
	# Enable the WhiteNoise storage backend, which compresses static files to reduce disk use
	# and renames the files with unique names for each version to support long-term caching
	STORAGES = {
		"staticfiles": {
			"BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
		},
	}

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# Email configuration
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_USE_TLS = True
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
SENDER_EMAIL = os.getenv('SENDER_EMAIL')

# CORS settings
#CORS_ALLOWED_ORIGINS = os.getenv('TRUSTED_ORIGINS').split(",")
CORS_ALLOW_ALL_ORIGINS = True
CORS_ALLOW_HEADERS = (
	*default_headers,
)
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = os.getenv('TRUSTED_ORIGINS').split(",")
CSRF_COOKIE_DOMAIN = os.getenv('COOKIE_DOMAINS').split(",")

imagekit = ImageKit(
	private_key=os.getenv('IMAGEKIT_PRIVATE'),
	public_key=os.getenv('IMAGEKIT_PUBLIC'),
	url_endpoint=os.getenv('IMAGEKIT_URL')
)

nltk.download('stopwords')
